import MultiSound from './MultiSound';

export const choiceSound = new MultiSound(`${process.env.PUBLIC_URL}/engine-assets/sfx/select00.wav`, 0.2);
export const selectSound = new MultiSound(`${process.env.PUBLIC_URL}/engine-assets/sfx/ok00.wav`, 0.2);
export const backSound = new MultiSound(`${process.env.PUBLIC_URL}/engine-assets/sfx/cancel00.wav`, 0.2);
// export const bossDeathQuiet = new MultiSound(`${process.env.PUBLIC_URL}/engine-assets/sfx/enep01.wav`, 0.2);
// export const bossDeathLoud = new MultiSound(`${process.env.PUBLIC_URL}/engine-assets/sfx/enep01.wav`, 0.6);
export const enemyDamage = new MultiSound(`${process.env.PUBLIC_URL}/engine-assets/sfx/damage00.wav`, 0.5, 2);
// export const enemyDeath = new MultiSound(`${process.env.PUBLIC_URL}/engine-assets/sfx/enep00.wav`, 0.2);
export const enemyShoot = new MultiSound(`${process.env.PUBLIC_URL}/engine-assets/sfx/tan00.wav`, 0.35, 1, 10);
// export const enemyChangeBullet = new MultiSound(`${process.env.PUBLIC_URL}/engine-assets/sfx/kira00.wav`, 0.20);
// export const minionSpawn = new MultiSound(`${process.env.PUBLIC_URL}/engine-assets/sfx/kira00.wav`, 0.20);
export const itemGet = new MultiSound(`${process.env.PUBLIC_URL}/engine-assets/sfx/seScore.wav`, 0.3);
// export const playerShoot = new LoopingSound(`${process.env.PUBLIC_URL}/engine-assets/sfx/plst00.wav`, 0.1, 2);
// export const playerBombCharge = new MultiSound(`${process.env.PUBLIC_URL}/engine-assets/sfx/power0.wav`, 0.5);
// export const playerBombCharge2 = new MultiSound(`${process.env.PUBLIC_URL}/engine-assets/sfx/power0.wav`, 0.3);
// export const playerMasterSpark = new MultiSound(`${process.env.PUBLIC_URL}/engine-assets/sfx/nep00.wav`, 1.0);
// export const playerBombShoot = new MultiSound(`${process.env.PUBLIC_URL}/engine-assets/sfx/tan00.wav`, 0.1);
// export const playerPowerUp = new MultiSound(`${process.env.PUBLIC_URL}/engine-assets/sfx/powerup.wav`, 0.3);
export const playerGraze = new MultiSound(`${process.env.PUBLIC_URL}/engine-assets/sfx/seGraze.wav`, 0.1);
export const playerDeath = new MultiSound(`${process.env.PUBLIC_URL}/engine-assets/sfx/Hidden.wav`, 0.1);
